#ifndef __cLoadoutPanel__
#define __cLoadoutPanel__

/**
@file
Subclass of LoadoutPanel, which is generated by wxFormBuilder.
*/

#include "cGui.h"

//// end generated include

/** Implementing LoadoutPanel */
class cLoadoutPanel : public LoadoutPanel
{
	protected:
		// Handlers for LoadoutPanel events.
		void onUniformChange( wxCommandEvent& event );
		void onBackpackChange( wxCommandEvent& event );
		void onPrimaryChange( wxCommandEvent& event );
		void onSecondaryChange( wxCommandEvent& event );
		void addCustomLinked( wxCommandEvent& event );
		void addPresetLinked( wxCommandEvent& event );
		void removePresetLinked( wxCommandEvent& event );
		void removeLinked( wxCommandEvent& event );
		void onVestChange( wxCommandEvent& event );
		void addCustomWeap( wxCommandEvent& event );
		void addPresetWeap( wxCommandEvent& event );
		void removePresetWeap( wxCommandEvent& event );
		void removeWeap( wxCommandEvent& event );
		void onHelmetChange( wxCommandEvent& event );
		void addCustomMag( wxCommandEvent& event );
		void addPresetMag( wxCommandEvent& event );
		void removePresetMag( wxCommandEvent& event );
		void updateMagAmount( wxCommandEvent& event );
		void removeMag( wxCommandEvent& event );
		void addCustomItem( wxCommandEvent& event );
		void addPresetItem( wxCommandEvent& event );
		void removePresetItem( wxCommandEvent& event );
		void updateItemAmount( wxCommandEvent& event );
		void removeItem( wxCommandEvent& event );
	public:
		/** Constructor */
		cLoadoutPanel( wxWindow* parent );

		friend class cMain;
	//// end generated class members

};

#endif // __cLoadoutPanel__
